name: ExecuteQuery build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.ODBC.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.ODBC.ExecuteQuery
      prebuild_command: Set-ExecutionPolicy RemoteSigned && .\Frends.ODBC.ExecuteQuery.Tests\TestFiles\odbc.ps1
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}