name: ExecuteQuery build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.ODBC.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.ODBC.ExecuteQuery
      prebuild_command: Set-ExecutionPolicy RemoteSigned && .\Frends.ODBC.ExecuteQuery.Tests\TestFiles\odbc.ps1
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}