name: ExecuteQuery build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.ODBC.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.ODBC.ExecuteQuery
      prebuild_command: Invoke-WebRequest -Uri 'https://download.microsoft.com/download/2/4/3/24375141-E08D-4803-AB0E-10F2E3A07AAA/AccessDatabaseEngine.exea' -OutFile 'AccessDatabaseEngine.exe' && Start-Process -FilePath 'AccessDatabaseEngine.exe' -ArgumentList '/quiet', 'iacceptaccesslicenseterms', 'addlocal="all"' && Add-OdbcDsn -Name "ODBC_testDB" -DriverName "Microsoft Access Driver (*.mdb, *.accdb)" -DsnType "User" -Platform "32-bit" -SetPropertyValue "Dbq=$pwd\TestFiles\ODBC_testDB_32.mdb"
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}