name: ExecuteQuery build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.ODBC.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  windows-build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.ODBC.ExecuteQuery
      prebuild_command: docker-compose -f /Frends.ODBC.ExecuteQuerty.Tests/docker-compose.yml up -d && .\_build\prebuild_script.ps1
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
  #linux-build:
  #  uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
  #  with:
  #    workdir: Frends.ODBC.ExecuteQuery
  #    prebuild_command: chmod 777 ./_build/prebuild_script.sh && ./_build/prebuild_script.sh
  #  secrets:
  #    badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
  #    test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}