name: ExecuteQuery build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.ODBC.ExecuteQuery/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.ODBC.ExecuteQuery
      prebuild_command: Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?linkid=2223303 -OutFile $pwd/odbc.msi && Start-Process -Filepath $pwd/odbc.msi -ArgumentList "/qr IACCEPTMSODBCSQLLICENSETERMS=YES" && Add-OdbcDsn -Name "ODBC_testDB" -DriverName "Microsoft Access Driver (*.mdb, *.accdb)" -DsnType "User" -Platform "32-bit" -SetPropertyValue 'Dbq=.\Frends.ODBC.ExecuteQuery.Tests\TestFiles\ODBC_testDB_32.mdb'
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}