version: '3'

services:
  linux:
    container_name: test-container
    build:
      context: .
    ports:
    - "8080:8080"
    volumes:
    - C:\Users\virtari\repos\Frends.ODBC\Frends.ODBC.ExecuteQuery:/usr/src/app/Frends.ODBC.ExecuteQuery